apiVersion: spark.dev/v1
kind: Connector
metadata:
  id: gmail
  name: "Ugmail"
  type: channel
  version: "1.0.0"
  source: spark
  publisher: "Spark"
  maintainers:
    - name: "Spark Team"
      email: "spark@kite.ai"
  category: "Communication"
  icon: mail
  description: "Spark gmail connector"
  license: MIT
spec:
  runtime:
    type: docker
    language: go
    sdk_language: go
    docker:
      image: ghcr.io/kite-production/connector-gmail
      tag: "1.0.0"
      image_available: true
